/* Generated By:JJTree&JavaCC: Do not edit this line. compiladorConstants.java */
package analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int CONSTANTE = 2;
  /** RegularExpression Id. */
  int VARIABLE = 3;
  /** RegularExpression Id. */
  int INPUT = 4;
  /** RegularExpression Id. */
  int PRINT = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int ASIGNACION = 11;
  /** RegularExpression Id. */
  int RESTA = 12;
  /** RegularExpression Id. */
  int SUMA = 13;
  /** RegularExpression Id. */
  int MULTIPLICACION = 14;
  /** RegularExpression Id. */
  int DIVISION = 15;
  /** RegularExpression Id. */
  int MENOR = 16;
  /** RegularExpression Id. */
  int MAYOR = 17;
  /** RegularExpression Id. */
  int MENORIGUAL = 18;
  /** RegularExpression Id. */
  int MAYORIGUAL = 19;
  /** RegularExpression Id. */
  int IGUAL = 20;
  /** RegularExpression Id. */
  int DIFERENTE = 21;
  /** RegularExpression Id. */
  int PARENTA = 22;
  /** RegularExpression Id. */
  int PARENTC = 23;
  /** RegularExpression Id. */
  int LLAVEA = 24;
  /** RegularExpression Id. */
  int LLAVEC = 25;
  /** RegularExpression Id. */
  int PCOMA = 26;
  /** RegularExpression Id. */
  int DCOMA = 27;
  /** RegularExpression Id. */
  int CORCHETEA = 28;
  /** RegularExpression Id. */
  int CORCHETEC = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int DECIMAL = 33;
  /** RegularExpression Id. */
  int CADENA = 34;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"start\"",
    "\"const\"",
    "\"var\"",
    "\"read\"",
    "\"write\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"||\"",
    "\"&&\"",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\"int\"",
    "\"float\"",
    "<NUMERO>",
    "<DECIMAL>",
    "<CADENA>",
    "<IDENTIFICADOR>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
