/* Generated By:JavaCC: Do not edit this line. compiladorTreeConstants.java Version 5.0 */
package analizador;

public interface compiladorTreeConstants
{
  public int JJTINICIARANALISISLEXICO = 0;
  public int JJTINICIARANALISISSINTACTICO = 1;
  public int JJTBLOQUE = 2;
  public int JJTDECLARARCONSTANTE = 3;
  public int JJTDECLARARVARIABLE = 4;
  public int JJTIDENTIFICADOR = 5;
  public int JJTOPERACION = 6;
  public int JJTTIPOINTEGER = 7;
  public int JJTTIPOFLOAT = 8;
  public int JJTVALORNUMEROENTERO = 9;
  public int JJTVALORNUMERODECIMAL = 10;
  public int JJTIMPRESION = 11;
  public int JJTASIGNACION = 12;
  public int JJTENTRADA = 13;
  public int JJTOPERADORMULTIPLICAR = 14;
  public int JJTOPERADORDIVIDIR = 15;
  public int JJTOPERADORSUMAR = 16;
  public int JJTOPERADORRESTAR = 17;
  public int JJTMENOR = 18;
  public int JJTMAYOR = 19;
  public int JJTIGUAL = 20;
  public int JJTMENORIGUAL = 21;
  public int JJTMAYORIGUAL = 22;
  public int JJTDIFERENTE = 23;
  public int JJTDECISIONIF = 24;
  public int JJTDECISIONELSE = 25;
  public int JJTEXPRESIONLOGICA = 26;
  public int JJTEXPRESIONSIMPLE = 27;
  public int JJTCICLOWHILE = 28;


  public String[] jjtNodeName = {
    "iniciarAnalisisLexico",
    "iniciarAnalisisSintactico",
    "bloque",
    "declararConstante",
    "declararVariable",
    "identificador",
    "operacion",
    "tipoInteger",
    "tipoFloat",
    "valorNumeroEntero",
    "valorNumeroDecimal",
    "impresion",
    "asignacion",
    "entrada",
    "operadorMultiplicar",
    "operadorDividir",
    "operadorSumar",
    "operadorRestar",
    "Menor",
    "Mayor",
    "Igual",
    "MenorIgual",
    "MayorIgual",
    "Diferente",
    "decisionIF",
    "decisionELSE",
    "expresionLogica",
    "expresionSimple",
    "cicloWhile",
  };
}
/* JavaCC - OriginalChecksum=7630916689bc26a05fbcc7c16546d5db (do not edit this line) */
